import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Global } from '@emotion/react';
import { EmotionRegistry } from '@/lib/EmotionRegistry';
import { globalStyles } from '@/styles/global-styles';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <EmotionRegistry>
          <Global styles={globalStyles} />
          {children}
        </EmotionRegistry>
      </body>
    </html>
  );
}
